server:
  port: 11000
logging:
  level:
    org: debug
keycloak:
  realm: SCPG #客户端所在的realm
  credentials:
    secret: J3wg0LQyH9YwW82mLhkFcC1GULQqs0nx
  auth-server-url: http://47.102.192.4:8080 #keycloak授权服务器地址
  resource: test-client #客户端名称
  #public-client: true #声明为一个公开的客户端
  #use-resource-role-mappings: true  #为true使用应用级角色映射
  security-constraints:
    - auth-roles:
        - default-roles-scpg
      security-collections:
        - name: hello
          patterns:
            - '/*'
  policy-enforcer-config:
    onDenyRedirectTo: '/access-denied'
spring:
  freemarker:
    cache: false
    # 模板后缀名
    suffix: .ftl
    # 文档类型
    content-type: text/html
    # 页面编码
    charset: UTF-8
    # 模板路径
    template-loader-path: classpath:/templates/
  main:
    banner-mode: OFF